name: DEV/INT Continuous Integration and Deployment Pipeline for Marketplace Management Service
on:
  push:
    branches:
      - '**' # Match all branches
      - '**'
  pull_request:
    branches:
      - '**'
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
permissions:
  id-token: write
  contents: read
jobs:
  dockerBuildAndPush:
    environment: ${{ github.event.inputs.environment || github.ref_name  }}
    runs-on:
      group: ${{ github.event.inputs.environment || github.ref_name == 'dev' && 'PIA-Runners-AzureVNet' || 'PIA' }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit id
        run: |
          COMMIT_ID="${GITHUB_SHA}"
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: ACR Login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            token=$(az acr login --name ${{ vars.ACR_SERVER }} --expose-token --output tsv --query accessToken)
            echo "ACR_TOKEN=$token" >> $GITHUB_ENV
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_SERVER }}
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ env.ACR_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ vars.ACR_SERVER }}/pia-des-org/app-pia-connector-ui:${{ env.COMMIT_ID }}
          no-cache: true